### ISSUE TITLE
The `add-path` command is disabled

### ISSUE THREAD

**Issue by devmount** [juliansangillo/version-composer#2]
At first: Thanks for this great action 👏🏻
When using this action, I get the following error:

![image](https://user-images.githubusercontent.com/5441654/107122199-87f07d00-6896-11eb-844b-949c6f565041.png)

I'm using this in my workflow:

```yml
- name: Version Composition
  id: v
  uses: juliansangillo/version-composer@v1
  with:
    revision-pattern: M.m
```

and in a later step access the composed version string like this:

    ${{ steps.v.outputs.raw-version }}

What to do?
